---
components:
  schemas:

    PressureTunnel:
      required:
        - id
        - type
      properties:
        id:
          type: string
          description: "Unique identifier of the PressureTunnel"
          maxLength: 256
          minLength: 1
          pattern: "^[\\w\\-\\.\\{\\}\\$\\+\\*\\[\\]`|~^@!,:\\\\]+$"
          x-ngsi:
            type: Property
        type:
          type: string
          enum:
            - PressureTunnel
          description: "Must be set to ‘PressureTunnel’"
          x-ngsi:
            type: Property
        length:
          type: object
          description: "Length of the pressure tunnel between reservoir and penstock (meters)"
          properties:
            value:
              type: number
              description: "Length value in meters"
            unitCode:
              type: string
              enum:
                - "M"
              description: "UN/CEFACT unit code for meter"
          x-ngsi:
            type: Property

        fromReservoir:
          type: array
          description: "Array of references to the upstream Reservoir entities"
          items:
            type: string
            format: uri
          x-ngsi:
            type: Relationship
        toPenstock:
          type: array
          description: "Array of references to the downstream Penstock entities"
          items:
            type: string
            format: uri
          x-ngsi:
            type: Relationship
        isPartOfHydroPowerPlant:
          type: array
          description: "Array of references to the HydropowerPlant entities of which this water body is a part"
          items:
            type: string
            format: uri
          x-ngsi:
            type: Relationship
      x-ngsi:
        uri-prefix: "https://raw.githubusercontent.com/satrai-lab/di-hydro-data-models/refs/heads/main/static/types-defenitions.json#"


info:
  description: "Data Model of PressureTunnel for Hydropower Plant Modeling"
  title: HydropowerPlantModeling
  version: "1.0.2"
openapi: "3.0.3"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        "200":
          content:
            application/ld+json:
              schema:
                type: object
          description: OK
